"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
type Subscription = { id: string; name: string; units: number; status: "意向认购" | "已缴款"; note: string };
type Transaction = { id: string; date: string; seller: string; buyer: string; units: number; price: number };
type Expense = { id: string; date: string; type: "收入" | "支出"; category: string; amount: number; note: string };
const unitPercent = 0.01, totalUnits = 100;
const sampleSubscriptions: Subscription[] = [{ id:"s1",name:"王先生",units:18,status:"意向认购",note:"等待统一确认" },{ id:"s2",name:"李女士",units:12,status:"意向认购",note:"" }];
const sampleExpenses: Expense[] = [{id:"e1",date:"2026-08-01",type:"收入",category:"销售收入",amount:46800,note:"当月累计"},{id:"e2",date:"2026-08-01",type:"支出",category:"原料采购",amount:12600,note:"面粉、黄油、奶油"},{id:"e3",date:"2026-08-01",type:"支出",category:"房租人工",amount:17200,note:"当月预计"}];
const money=(n:number)=>new Intl.NumberFormat("zh-CN",{style:"currency",currency:"CNY",maximumFractionDigits:2}).format(n); const today=()=>new Date().toISOString().slice(0,10);
export default function Home(){
 const [subscriptions,setSubscriptions]=useState<Subscription[]>(sampleSubscriptions),[transactions,setTransactions]=useState<Transaction[]>([]),[expenses,setExpenses]=useState<Expense[]>(sampleExpenses),[initialInvestment,setInitialInvestment]=useState(650000),[openForm,setOpenForm]=useState<"subscription"|"transaction"|"expense"|null>(null),[activeTab,setActiveTab]=useState<"overview"|"subscriptions"|"transactions"|"expenses">("overview");
 useEffect(()=>{const stored=localStorage.getItem("bread-share-ledger-v1");if(stored)try{const d=JSON.parse(stored);setSubscriptions(d.subscriptions??sampleSubscriptions);setTransactions(d.transactions??[]);setExpenses(d.expenses??sampleExpenses);setInitialInvestment(d.initialInvestment??650000)}catch{}},[]);
 useEffect(()=>localStorage.setItem("bread-share-ledger-v1",JSON.stringify({subscriptions,transactions,expenses,initialInvestment})),[subscriptions,transactions,expenses,initialInvestment]);
 const income=expenses.filter(x=>x.type==="收入").reduce((s,x)=>s+x.amount,0),outgo=expenses.filter(x=>x.type==="支出").reduce((s,x)=>s+x.amount,0),netProfit=income-outgo,subscribedUnits=subscriptions.reduce((s,x)=>s+x.units,0),paidUnits=subscriptions.filter(x=>x.status==="已缴款").reduce((s,x)=>s+x.units,0),sharePoolValue=initialInvestment*.01+netProfit*.01,unitValue=sharePoolValue/totalUnits,dividendPool=Math.max(0,netProfit*.01),unitsRemaining=totalUnits-subscribedUnits;
 const investorRows=useMemo(()=>{const h=new Map<string,number>();subscriptions.forEach(s=>h.set(s.name,(h.get(s.name)??0)+s.units));transactions.forEach(t=>{h.set(t.seller,(h.get(t.seller)??0)-t.units);h.set(t.buyer,(h.get(t.buyer)??0)+t.units)});return[...h.entries()].filter(([,u])=>u!==0).map(([name,units])=>({name,units}))},[subscriptions,transactions]);
 function sub(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),units=Number(f.get("units"));if(!f.get("name")||units<=0||units>unitsRemaining)return;setSubscriptions(x=>[...x,{id:crypto.randomUUID(),name:String(f.get("name")),units,status:String(f.get("status")) as Subscription["status"],note:String(f.get("note")||"")}]);setOpenForm(null)}
 function trade(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),units=Number(f.get("units")),price=Number(f.get("price"));if(!f.get("seller")||!f.get("buyer")||units<=0||price<0)return;setTransactions(x=>[...x,{id:crypto.randomUUID(),date:String(f.get("date")),seller:String(f.get("seller")),buyer:String(f.get("buyer")),units,price}]);setOpenForm(null)}
 function expense(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),amount=Number(f.get("amount"));if(!f.get("category")||amount<=0)return;setExpenses(x=>[...x,{id:crypto.randomUUID(),date:String(f.get("date")),type:String(f.get("type")) as Expense["type"],category:String(f.get("category")),amount,note:String(f.get("note")||"")}]);setOpenForm(null)}
 const remove=(type:"subscription"|"transaction"|"expense",id:string)=>{if(!confirm("确认删除这条记录？"))return;if(type==="subscription")setSubscriptions(x=>x.filter(v=>v.id!==id));if(type==="transaction")setTransactions(x=>x.filter(v=>v.id!==id));if(type==="expense")setExpenses(x=>x.filter(v=>v.id!==id))};
 const title=activeTab==="overview"?"店铺与股份总览":activeTab==="subscriptions"?"认购意向":activeTab==="transactions"?"股份交易流水":"收入与花费";
 return <main><aside className="sidebar"><div className="brand"><span className="brand-mark">麦</span><div><strong>麦穗股份簿</strong><small>面包店 · 内部管理</small></div></div><nav>{([['overview','总览'],['subscriptions','认购登记'],['transactions','股份交易'],['expenses','收支明细']] as const).map(([id,label])=><button key={id} className={activeTab===id?"active":""} onClick={()=>setActiveTab(id)}>{label}</button>)}</nav><div className="side-note"><span>股份池</span><b>1.00%</b><small>最小单位：0.01%</small></div></aside><section className="content"><header><div><p className="eyebrow">每日经营看板 · {today()}</p><h1>{title}</h1></div><button className="primary" onClick={()=>setOpenForm(activeTab==="transactions"?"transaction":activeTab==="expenses"?"expense":"subscription")}>＋ 新增记录</button></header>
 {activeTab==="overview"&&<><section className="notice"><span>认购期进行中</span><p>目前仅登记意向，统一安排完成后再收款。已认购 <b>{(subscribedUnits*unitPercent).toFixed(2)}%</b>，剩余 <b>{(unitsRemaining*unitPercent).toFixed(2)}%</b> 可供认购。</p></section><section className="metrics"><Metric label="本月净利润" value={money(netProfit)} hint={`收入 ${money(income)} · 支出 ${money(outgo)}`} tone={netProfit>=0?"green":"red"}/><Metric label="1%股份估值" value={money(sharePoolValue)} hint="初始出资 + 本月净利润的 1%"/><Metric label="每 0.01% 估值" value={money(unitValue)} hint="基于当前市值"/><Metric label="月底预期分红 / 单位" value={money(dividendPool/totalUnits)} hint="按本月净利润的 1%预估" tone="gold"/></section><section className="two-col"><article className="card"><div className="card-head"><div><p className="eyebrow">持仓名册</p><h2>当前股份归属</h2></div><span>{investorRows.length} 位持有人</span></div>{investorRows.length?<div className="holdings">{investorRows.map(x=><div key={x.name}><span className="avatar">{x.name.slice(0,1)}</span><b>{x.name}</b><small>{(x.units*unitPercent).toFixed(2)}%</small><strong>{money(x.units*unitValue)}</strong></div>)}</div>:<Empty text="认购后将在此显示持仓"/>}</article><article className="card"><div className="card-head"><div><p className="eyebrow">分红预测</p><h2>月底预期分配</h2></div></div><div className="dividend"><span>可分配股东利润池</span><strong>{money(dividendPool)}</strong><small>规则：将当月净利润的 1%按持有单位比例分配。可在收支明细中更新真实经营数据。</small></div><div className="formula">持有单位 × {money(dividendPool/totalUnits)} = 本月预期分红</div></article></section><section className="card valuation"><div><p className="eyebrow">估值依据</p><h2>股份价值如何计算？</h2></div><p><b>初始估值：</b>店铺开办资金 {money(initialInvestment)} × 1% = {money(initialInvestment*.01)}。<b>当前估值：</b>初始股份价值 + 累计经营盈亏的 1%，再除以 100 个最小单位。</p><label>开办资金<input type="number" value={initialInvestment} onChange={e=>setInitialInvestment(Number(e.target.value)||0)}/></label></section></>}
 {activeTab==="subscriptions"&&<Records title="认购记录" subtitle={`可认购 ${unitsRemaining} 个单位（${(unitsRemaining*unitPercent).toFixed(2)}%）`} headers={["认购人","认购股份","参考金额","状态","备注",""]} empty="尚未登记认购意向">{subscriptions.map(x=><tr key={x.id}><td><b>{x.name}</b></td><td>{x.units} 单位 <small>({(x.units*unitPercent).toFixed(2)}%)</small></td><td>{money(x.units*unitValue)}</td><td><span className={x.status==="已缴款"?"badge paid":"badge"}>{x.status}</span></td><td>{x.note||"—"}</td><td><button className="delete" onClick={()=>remove("subscription",x.id)}>删除</button></td></tr>)}</Records>}
 {activeTab==="transactions"&&<Records title="交易流水" subtitle="交易不会改变总股份数，只变更归属和成交参考价" headers={["日期","转让方","受让方","股份","成交金额","成交单价",""]} empty="暂无股份交易记录">{transactions.map(x=><tr key={x.id}><td>{x.date}</td><td><b>{x.seller}</b></td><td><b>{x.buyer}</b></td><td>{(x.units*unitPercent).toFixed(2)}%</td><td>{money(x.price)}</td><td>{money(x.price/x.units)}</td><td><button className="delete" onClick={()=>remove("transaction",x.id)}>删除</button></td></tr>)}</Records>}
 {activeTab==="expenses"&&<Records title="经营收支" subtitle="这些数据用于计算当月净利润、估值和预期分红" headers={["日期","类型","分类","金额","说明",""]} empty="暂无收支记录">{[...expenses].sort((a,b)=>b.date.localeCompare(a.date)).map(x=><tr key={x.id}><td>{x.date}</td><td><span className={x.type==="收入"?"income":"expense"}>{x.type}</span></td><td><b>{x.category}</b></td><td className={x.type==="收入"?"income":"expense"}>{x.type==="收入"?"+":"−"}{money(x.amount)}</td><td>{x.note||"—"}</td><td><button className="delete" onClick={()=>remove("expense",x.id)}>删除</button></td></tr>)}</Records>}
 </section>{openForm&&<div className="modal-backdrop" onMouseDown={()=>setOpenForm(null)}><form className="modal" onSubmit={openForm==="subscription"?sub:openForm==="transaction"?trade:expense} onMouseDown={e=>e.stopPropagation()}><button type="button" className="close" onClick={()=>setOpenForm(null)}>×</button><p className="eyebrow">新增记录</p><h2>{openForm==="subscription"?"登记认购意向":openForm==="transaction"?"登记股份交易":"登记经营收支"}</h2>{openForm==="subscription"&&<><label>认购人<input name="name" required placeholder="姓名或称呼"/></label><label>认购单位（1单位 = 0.01%）<input name="units" type="number" min="1" max={unitsRemaining} required/></label><label>状态<select name="status"><option>意向认购</option><option>已缴款</option></select></label><label>备注<input name="note" placeholder="可选"/></label></>}{openForm==="transaction"&&<><label>交易日期<input name="date" type="date" defaultValue={today()} required/></label><label>转让方<input name="seller" required/></label><label>受让方<input name="buyer" required/></label><label>交易单位<input name="units" type="number" min="1" required/></label><label>成交总金额<input name="price" type="number" min="0" step="0.01" required/></label></>}{openForm==="expense"&&<><label>日期<input name="date" type="date" defaultValue={today()} required/></label><label>类型<select name="type"><option>收入</option><option>支出</option></select></label><label>分类<input name="category" required placeholder="例如：原料采购"/></label><label>金额<input name="amount" type="number" min="0.01" step="0.01" required/></label><label>说明<input name="note" placeholder="可选"/></label></>}<button className="primary submit">保存记录</button></form></div>}</main>;
}
function Metric({label,value,hint,tone=""}:{label:string;value:string;hint:string;tone?:string}){return <article className={`metric ${tone}`}><p>{label}</p><strong>{value}</strong><small>{hint}</small></article>}; function Empty({text}:{text:string}){return <div className="empty">{text}</div>}; function Records({title,subtitle,headers,empty,children}:{title:string;subtitle:string;headers:string[];empty:string;children:React.ReactNode[]}){return <section className="card records"><div className="card-head"><div><p className="eyebrow">数据管理</p><h2>{title}</h2><small>{subtitle}</small></div></div>{children.length?<div className="table-wrap"><table><thead><tr>{headers.map((x,i)=><th key={i}>{x}</th>)}</tr></thead><tbody>{children}</tbody></table></div>:<Empty text={empty}/>}</section>}
