"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { AccessGate } from "./access-gate";

type Subscription={id:string;name:string;units:number;value:number;status:"意向认购"|"已确认持有";note:string}; type Tx={id:string;date:string;seller:string;buyer:string;units:number;price:number}; type Expense={id:string;date:string;type:"收入"|"支出";category:string;amount:number;note:string}; type Settings={initial_investment:number;dividend_ratio:number;profit_mapping_ratio:number}; type Ledger={settings:Settings;subscriptions:Subscription[];transactions:Tx[];expenses:Expense[]};
const money=(n:number)=>new Intl.NumberFormat("zh-CN",{style:"currency",currency:"CNY",maximumFractionDigits:2}).format(n);const today=()=>new Date().toISOString().slice(0,10);const pct=(u:number)=>(u*.01).toFixed(2)+"%";
function LedgerHome(){
 const [data,setData]=useState<Ledger|null>(null),[tab,setTab]=useState<"overview"|"subscriptions"|"holdings"|"transactions"|"expenses">("overview"),[form,setForm]=useState<"subscription"|"transaction"|"expense"|"settings"|null>(null),[error,setError]=useState("");
 const load=async()=>{const r=await fetch("/api/ledger",{cache:"no-store"});const j=await r.json();if(j.error)throw new Error(j.error);setData(j)};useEffect(()=>{load().catch(e=>setError(e.message));const t=setInterval(()=>load().catch(()=>{}),15000);return()=>clearInterval(t)},[]);
 const mutate=async(action:string,payload:Record<string,unknown>)=>{setError("");const r=await fetch("/api/ledger",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,payload})});const j=await r.json();if(!r.ok)throw new Error(j.error||"保存失败");setData(j);};
 const netProfit=useMemo(()=>data?data.expenses.reduce((s,x)=>s+(x.type==="收入"?x.amount:-x.amount),0):0,[data]); const confirmed=data?.subscriptions.filter(x=>x.status==="已确认持有")??[];const confirmedValue=confirmed.reduce((s,x)=>s+x.value,0);const initial=data?.settings.initial_investment??650000;const mapping=(data?.settings.profit_mapping_ratio??100)/100;const marketCap=initial+netProfit*mapping+confirmedValue;const unitValue=marketCap/10000;const dividendPerUnit=Math.max(0,netProfit)*(data?.settings.dividend_ratio??90)/100/10000;
 const holdings=useMemo(()=>{const h=new Map<string,number>();confirmed.forEach(x=>h.set(x.name,(h.get(x.name)??0)+x.units));data?.transactions.forEach(x=>{h.set(x.seller,(h.get(x.seller)??0)-x.units);h.set(x.buyer,(h.get(x.buyer)??0)+x.units)});return[...h.entries()].filter(([,u])=>u>0).map(([name,units])=>({name,units}))},[confirmed,data?.transactions]);const available=100-(data?.subscriptions.reduce((s,x)=>s+x.units,0)??0);const holderNames=holdings.map(x=>x.name);
 if(!data)return <main><section className="loading">正在连接共享账本…{error&&<small>{error}</small>}</section></main>;
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{if(form==="subscription")await mutate("subscription:add",{name:f.get("name"),units:Number(f.get("units")),value:Number(f.get("value")),note:f.get("note")});if(form==="transaction")await mutate("transaction:add",{date:f.get("date"),seller:f.get("seller"),buyer:f.get("buyer"),units:Number(f.get("units")),price:Number(f.get("price"))});if(form==="expense")await mutate("expense:add",{date:f.get("date"),type:f.get("type"),category:f.get("category"),amount:Number(f.get("amount")),note:f.get("note")});if(form==="settings")await mutate("settings:update",{initialInvestment:Number(f.get("initialInvestment")),dividendRatio:Number(f.get("dividendRatio")),profitMappingRatio:Number(f.get("profitMappingRatio"))});setForm(null)}catch(e){setError(e instanceof Error?e.message:"保存失败")}};
 const confirm=async(id:string)=>{try{await mutate("subscription:confirm",{id})}catch(e){setError(e instanceof Error?e.message:"确认失败")}};const remove=async(type:string,id:string)=>{if(!confirm("确认删除这条记录？"))return;try{await mutate(`${type}:delete`,{id})}catch(e){setError(e instanceof Error?e.message:"删除失败")}};
 const title={overview:"店铺与股份总览",subscriptions:"认购登记",holdings:"股份持有",transactions:"股份交易",expenses:"收支明细"}[tab];
 return <main><aside className="sidebar"><div className="brand"><span className="brand-mark">麦</span><div><strong>麦穗股份簿</strong><small>面包店 · 共享账本</small></div></div><nav>{([['overview','总览'],['subscriptions','认购登记'],['holdings','股份持有'],['transactions','股份交易'],['expenses','收支明细']] as const).map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</nav><div className="side-note"><span>出售股份池</span><b>1.00%</b><small>最小单位：0.01%</small></div></aside><section className="content"><header><div><p className="eyebrow">共享云端账本 · 每 15 秒同步 · {today()}</p><h1>{title}</h1></div><button className="primary" onClick={()=>setForm(tab==="transactions"?"transaction":tab==="expenses"?"expense":tab==="overview"?"settings":"subscription")}>＋ {tab==="overview"?"设置规则":"新增记录"}</button></header>{error&&<div className="error">{error}<button onClick={()=>setError("")}>×</button></div>}
 {tab==="overview"&&<><section className="notice"><span>共享模式</span><p>访问此网址的成员可登记和修改账本；所有页面会自动同步最新数据。</p></section><section className="metrics"><Metric label="当前总市值" value={money(marketCap)} hint="65万 + 净利润映射 + 已确认认购价值"/><Metric label="本期净利润" value={money(netProfit)} hint={`净利润映射比例 ${data.settings.profit_mapping_ratio}%`} tone={netProfit>=0?"green":"red"}/><Metric label="每 0.01% 股份价值" value={money(unitValue)} hint="总市值 ÷ 10,000"/><Metric label="预期每股分红" value={money(dividendPerUnit)} hint={`净利润分红比例 ${data.settings.dividend_ratio}%`} tone="gold"/></section><section className="two-col"><article className="card"><div className="card-head"><div><p className="eyebrow">股份持有</p><h2>确认后自动进入持有名册</h2></div><span>{holdings.length} 位持有人</span></div>{holdings.length?<div className="holdings">{holdings.map(x=><div key={x.name}><span className="avatar">{x.name.slice(0,1)}</span><b>{x.name}</b><small>{pct(x.units)}</small><strong>{money(x.units*unitValue)}</strong></div>)}</div>:<Empty text="确认认购后将在此显示持仓"/>}</article><article className="card"><div className="card-head"><div><p className="eyebrow">分红与估值规则</p><h2>本期计算</h2></div></div><div className="dividend"><span>股东预期分红池</span><strong>{money(Math.max(0,netProfit)*(data.settings.dividend_ratio/100)*.01)}</strong><small>净利润 × 分红比例 × 1%（出售股份池）</small></div><div className="formula">{money(Math.max(0,netProfit))} × {data.settings.dividend_ratio}% ÷ 10,000 = {money(dividendPerUnit)} / 单位</div></article></section><section className="card valuation"><div><p className="eyebrow">市值公式</p><h2>可调整的计算参数</h2></div><p><b>总市值 =</b> {money(initial)} + {money(netProfit)} × {data.settings.profit_mapping_ratio}% + {money(confirmedValue)}（已确认认购股份价值）。股份交易只转移持有人，不改变该认购价值。</p><button className="secondary" onClick={()=>setForm("settings")}>调整分红与映射比例</button></section></>}
 {tab==="subscriptions"&&<Records title="认购登记" subtitle={`尚余 ${available} 单位（${pct(available)}）可供认购；确认后将生成股份持有记录`} headers={["认购人","股份","认购价值","状态","备注","操作"]} empty="尚未登记认购意向">{data.subscriptions.map(x=><tr key={x.id}><td><b>{x.name}</b></td><td>{x.units} 单位 <small>({pct(x.units)})</small></td><td>{money(x.value)}</td><td><span className={x.status==="已确认持有"?"badge paid":"badge"}>{x.status}</span></td><td>{x.note||"—"}</td><td>{x.status==="意向认购"&&<button className="confirm" onClick={()=>confirm(x.id)}>确认持有</button>}<button className="delete" onClick={()=>remove("subscription",x.id)}>删除</button></td></tr>)}</Records>}
 {tab==="holdings"&&<Records title="股份持有名册" subtitle="由已确认认购与全部股份交易自动计算，不能直接修改" headers={["持有人","持有单位","股份比例","当前股份价值","月底预期分红"]} empty="尚无已确认的股份持有记录">{holdings.map(x=><tr key={x.name}><td><b>{x.name}</b></td><td>{x.units} 单位</td><td>{pct(x.units)}</td><td>{money(x.units*unitValue)}</td><td className="income">{money(x.units*dividendPerUnit)}</td></tr>)}</Records>}
 {tab==="transactions"&&<Records title="股份交易流水" subtitle="交易完成后会立即改变双方的股份持有；不会改变认购股份价值或总市值" headers={["日期","转让方","受让方","股份","成交金额","成交单价","操作"]} empty="暂无股份交易记录">{data.transactions.map(x=><tr key={x.id}><td>{x.date}</td><td><b>{x.seller}</b></td><td><b>{x.buyer}</b></td><td>{pct(x.units)}</td><td>{money(x.price)}</td><td>{money(x.price/x.units)}</td><td><button className="delete" onClick={()=>remove("transaction",x.id)}>删除</button></td></tr>)}</Records>}
 {tab==="expenses"&&<Records title="经营收支" subtitle="收支会影响净利润、总市值映射和预期分红" headers={["日期","类型","分类","金额","说明","操作"]} empty="暂无收支记录">{data.expenses.map(x=><tr key={x.id}><td>{x.date}</td><td><span className={x.type==="收入"?"income":"expense"}>{x.type}</span></td><td><b>{x.category}</b></td><td className={x.type==="收入"?"income":"expense"}>{x.type==="收入"?"+":"−"}{money(x.amount)}</td><td>{x.note||"—"}</td><td><button className="delete" onClick={()=>remove("expense",x.id)}>删除</button></td></tr>)}</Records>}
 </section>{form&&<div className="modal-backdrop" onMouseDown={()=>setForm(null)}><form className="modal" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><button type="button" className="close" onClick={()=>setForm(null)}>×</button><p className="eyebrow">共享账本</p><h2>{form==="subscription"?"登记认购意向":form==="transaction"?"登记股份交易":form==="expense"?"登记经营收支":"调整计算规则"}</h2>{form==="subscription"&&<><label>认购人<input name="name" required/></label><label>认购单位（1单位 = 0.01%）<input name="units" type="number" min="1" max={available} required/></label><label>认购股份价值（元）<input name="value" type="number" min="0" step="0.01" defaultValue={65} required/></label><label>备注<input name="note"/></label></>}{form==="transaction"&&<>{holderNames.length<2?<p className="form-note">请先确认至少两位认购人，才可登记股份交易。</p>:<><label>交易日期<input name="date" type="date" defaultValue={today()} required/></label><label>转让方<select name="seller" required>{holderNames.map(x=><option key={x}>{x}</option>)}</select></label><label>受让方<select name="buyer" required>{holderNames.map(x=><option key={x}>{x}</option>)}</select></label><label>交易单位<input name="units" type="number" min="1" required/></label><label>成交总金额（元）<input name="price" type="number" min="0" step="0.01" required/></label></>}</>}{form==="expense"&&<><label>日期<input name="date" type="date" defaultValue={today()} required/></label><label>类型<select name="type"><option>收入</option><option>支出</option></select></label><label>分类<input name="category" required placeholder="例如：原料采购"/></label><label>金额（元）<input name="amount" type="number" min="0.01" step="0.01" required/></label><label>说明<input name="note"/></label></>}{form==="settings"&&<><label>开办资金（元）<input name="initialInvestment" type="number" min="0" defaultValue={data.settings.initial_investment} required/></label><label>净利润分红比例（%）<input name="dividendRatio" type="number" min="0" max="100" step="0.1" defaultValue={data.settings.dividend_ratio} required/></label><label>净利润映射比例（%）<input name="profitMappingRatio" type="number" min="0" step="0.1" defaultValue={data.settings.profit_mapping_ratio} required/></label><p className="form-note">例：净利润 10,000 元、分红比例 90%，则每 0.01% 预期分红 0.9 元。</p></>}<button className="primary submit" disabled={form==="transaction"&&holderNames.length<2}>保存并同步</button></form></div>}</main>;
}
function Metric({label,value,hint,tone=""}:{label:string;value:string;hint:string;tone?:string}){return <article className={`metric ${tone}`}><p>{label}</p><strong>{value}</strong><small>{hint}</small></article>};function Empty({text}:{text:string}){return <div className="empty">{text}</div>};function Records({title,subtitle,headers,empty,children}:{title:string;subtitle:string;headers:string[];empty:string;children:React.ReactNode[]}){return <section className="card records"><div className="card-head"><div><p className="eyebrow">数据管理</p><h2>{title}</h2><small>{subtitle}</small></div></div>{children.length?<div className="table-wrap"><table><thead><tr>{headers.map((x,i)=><th key={i}>{x}</th>)}</tr></thead><tbody>{children}</tbody></table></div>:<Empty text={empty}/>}</section>}
export default function Home(){return <AccessGate><LedgerHome/></AccessGate>}
